"""Convert Claude conversations into sources that are added to context cards.

A conversation becomes a SOURCE in a card. Multiple sources (files, conversations,
tests, chat history) are combined into one card by FileContextStore's deduplication.

Card metadata (title, description, keywords) is generated by CardMetadataGenerator
based on all sources together, not per-conversation.

See CardMetadataGenerator for how metadata is created and refreshed.
"""
from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Optional


class ConversationCardBuilder:
    """Create conversation sources for context cards.

    A conversation source goes into a card. The card combines multiple sources
    (files, conversations, tests, chat history, etc.) and has unified metadata
    generated by CardMetadataGenerator based on all sources together.
    """

    def __init__(self, cards_dir: str, corpus_root: Optional[str] = None):
        """Initialize the builder.

        Args:
            cards_dir: Directory where cards are written (JSON files).
            corpus_root: Corpus root for relative path resolution.
        """
        self.cards_dir = Path(cards_dir)
        self.corpus_root = Path(corpus_root) if corpus_root else None
        self.cards_dir.mkdir(parents=True, exist_ok=True)

    def build_conversation_source(
        self, conv_id: str, conv: Dict[str, Any], conv_file_path: str
    ) -> Dict[str, Any]:
        """Build a conversation source entry for a card.

        Args:
            conv_id: Conversation identifier
            conv: Conversation dict with messages/turns
            conv_file_path: Path to the conversation file

        Returns:
            Source dict to be added to a card's "sources" array
        """
        # Compute file hash
        try:
            file_hash = hashlib.sha256(str(conv).encode()).hexdigest()
        except Exception:
            file_hash = ""

        messages = self._get_messages(conv)
        return {
            "type": "conversation",
            "id": conv_id,
            "path": conv_file_path,
            "sha256": file_hash,
            "turn_count": len(messages),
            "why": "Claude conversation",
        }

    def create_card_with_conversation(
        self, conv_id: str, conv: Dict[str, Any], conv_file_path: str
    ) -> Dict[str, Any]:
        """Create a new card with a conversation source.

        Note: Card metadata (title, description, keywords) should be generated
        by CardMetadataGenerator, not here.

        Args:
            conv_id: Conversation identifier
            conv: Conversation dict
            conv_file_path: Path to the conversation file

        Returns:
            Basic card dict (metadata not yet generated)
        """
        source = self.build_conversation_source(conv_id, conv, conv_file_path)

        card = {
            "id": conv_id,
            "sources": [source],
            "title": "",  # To be filled by CardMetadataGenerator
            "description": "",  # To be filled by CardMetadataGenerator
            "keywords": [],  # To be filled by CardMetadataGenerator
            "conventions": [],
            "provenance": {
                "created_by_task": "conversation_card_builder",
                "model": conv.get("model_hint") or "unknown",
                "created_at": datetime.now(timezone.utc).isoformat(),
                "last_verified_at": datetime.now(timezone.utc).isoformat(),
            },
            "usage_count": 0,
            "last_outcome": "unknown",
        }

        return card

    def write_card(self, card: Dict[str, Any]) -> Path:
        """Write a card to disk.

        Returns:
            Path to the written card file
        """
        card_file = self.cards_dir / f"{card['id']}.json"
        card_file.write_text(json.dumps(card, indent=2))
        return card_file

    def build_and_write(
        self, conv_id: str, conv: Dict[str, Any], conv_file_path: str
    ) -> Optional[Path]:
        """Create a card with a conversation source and write it.

        Returns:
            Path to written card, or None on error
        """
        try:
            card = self.create_card_with_conversation(conv_id, conv, conv_file_path)
            return self.write_card(card)
        except Exception:  # noqa: BLE001
            return None

    @staticmethod
    def _get_messages(conv: Dict[str, Any]) -> list:
        """Extract messages from conversation dict."""
        return conv.get("messages") or conv.get("turns") or []
